// trainData.js

const arrivalTimes = {

	tuesday: [

		{ destination: '仙林湖', time: "06:10:00", jiaolu: "大交路" },
		{ destination: '东流', time: "06:15:00", jiaolu: "小交路" }, // 为之前缺失 jiaolu 属性的对象添加了 jiaolu 属性，可根据实际情况修改
		{ destination: '仙林湖', time: "06:21:00", jiaolu: "大交路" },
		{ destination: '东流', time: "06:27:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "06:32:00", jiaolu: "大交路" },
		{ destination: '东流', time: "06:38:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "06:44:00", jiaolu: "大交路" },
		{ destination: '东流', time: "06:49:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "06:55:00", jiaolu: "大交路" },

		{ destination: '东流', time: "07:01:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "07:06:00", jiaolu: "大交路" },
		{ destination: '东流', time: "07:12:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "07:18:00", jiaolu: "大交路" },
		{ destination: '东流', time: "07:23:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "07:29:00", jiaolu: "大交路" },
		{ destination: '东流', time: "07:35:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "07:40:00", jiaolu: "大交路" },
		{ destination: '东流', time: "07:46:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "07:52:00", jiaolu: "大交路" },
		{ destination: '东流', time: "07:57:00", jiaolu: "小交路" },

		{ destination: '仙林湖', time: "08:03:00", jiaolu: "大交路" },
		{ destination: '东流', time: "08:09:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "08:14:00", jiaolu: "大交路" },
		{ destination: '东流', time: "08:20:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "08:26:00", jiaolu: "大交路" },
		{ destination: '东流', time: "08:31:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "08:37:00", jiaolu: "大交路" },
		{ destination: '东流', time: "08:43:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "08:48:00", jiaolu: "大交路" },
		{ destination: '东流', time: "08:54:00", jiaolu: "小交路" },

		{ destination: '仙林湖', time: "09:00:00", jiaolu: "大交路" },
		{ destination: '东流', time: "09:05:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "09:11:00", jiaolu: "大交路" },
		{ destination: '东流', time: "09:16:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "09:22:00", jiaolu: "大交路" },
		{ destination: '东流', time: "09:28:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "09:33:00", jiaolu: "大交路" },
		{ destination: '东流', time: "09:39:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "09:45:00", jiaolu: "大交路" },
		{ destination: '东流', time: "09:50:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "09:56:00", jiaolu: "大交路" },

		{ destination: '仙林湖', time: "10:02:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "10:07:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "10:13:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "10:19:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "10:24:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "10:30:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "10:36:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "10:41:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "10:47:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "10:53:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "10:58:00", jiaolu: "大交路" },

		{ destination: '仙林湖', time: "11:04:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "11:10:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "11:15:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "11:21:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "11:27:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "11:32:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "11:38:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "11:44:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "11:49:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "11:55:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "12:01:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "12:06:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "12:12:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "12:18:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "12:23:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "12:29:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "12:35:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "12:40:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "12:46:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "12:52:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "12:57:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "13:00:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "13:09:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "13:14:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "13:20:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "13:26:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "13:31:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "13:37:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "13:43:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "13:48:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "13:56:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "14:00:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "14:05:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "14:11:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "14:17:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "14:22:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "14:28:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "14:34:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "14:39:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "14:45:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "14:51:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "14:56:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "15:02:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "15:08:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "15:13:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "15:19:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "15:25:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "15:30:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "15:33:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "15:36:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "15:41:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "15:53:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "15:59:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:01:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:06:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "16:11:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:16:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "16:21:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:26:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "16:31:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:36:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "16:41:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:45:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "16:50:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "16:55:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:00:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "17:05:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:10:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "17:14:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:19:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "17:24:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:30:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "17:35:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:40:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "17:45:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:50:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "17:54:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "17:59:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "18:04:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "18:09:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "18:14:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "18:19:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "18:24:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "18:28:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "18:33:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "18:38:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "18:43:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "18:48:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "18:53:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "18:58:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "19:03:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "19:08:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "19:14:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "19:20:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "19:26:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "19:32:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "19:38:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "19:43:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "19:48:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "19:54:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "19:59:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "20:05:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "20:11:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "20:16:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "20:22:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "20:28:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "20:33:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "20:39:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "20:45:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "20:50:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "20:56:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "21:00:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "21:10:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "21:19:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "21:28:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "21:37:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "21:46:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "21:54:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "22:03:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "22:12:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "22:21:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "22:29:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "22:38:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "22:47:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "22:55:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "23:04:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "23:12:00", jiaolu: "大交路" },
		{ destination: '仙林湖', time: "23:21:00", jiaolu: "小交路" },
		{ destination: '仙林湖', time: "23:29:00", jiaolu: "大交路" },
		{ destination: '仙林湖（末班车）', time: "23:37:00", jiaolu: "小交路" },

],
	monday: [
	        { destination: '终点站E', time: "11:00:00", jiaolu: "模式A" },
	        { destination: '终点站F', time: "11:30:00", jiaolu: "模式B" },
	    ],
    wednesday: [
        { destination: '终点站G', time: "12:00:00", jiaolu: "模式A" },
        { destination: '终点站H', time: "12:30:00", jiaolu: "模式B" },
    ],
    thursday: [
        { destination: '终点站I', time: "13:00:00", jiaolu: "模式A" },
        { destination: '终点站J', time: "13:30:00", jiaolu: "模式B" },
    ],
    friday: [
        { destination: '终点站K', time: "14:00:00", jiaolu: "模式A" },
        { destination: '终点站L', time: "14:30:00", jiaolu: "模式B" },
    ],
    sunday: [
        { destination: '终点站M', time: "15:00:00", jiaolu: "模式A" },
        { destination: '终点站N', time: "15:10:00", jiaolu: "模式B" },
        { destination: '终点站M', time: "15:13:00", jiaolu: "模式A" },
        { destination: '终点站N', time: "15:14:00", jiaolu: "模式B" },
        { destination: '终点站M', time: "15:16:00", jiaolu: "模式A" },
        { destination: '终点站N', time: "15:17:00", jiaolu: "模式B" },
        { destination: '终点站M', time: "15:24:00", jiaolu: "模式A" },
 
    ],
    saturday: [
        { destination: '终点站A', time: "10:00:00", jiaolu: "模式A" },
        { destination: '终点站B', time: "10:15:00", jiaolu: "模式B" },
    ],

};

export default arrivalTimes;










